### ISSUE TITLE
which version of node & npm used in this project ?

### ISSUE THREAD

**Issue by todokku** [bitwave-tv/bitwave#102]
Hi bitwave ,
which version of node & npm used in this project ?
waiting for your response
finest regards
goodbye

**Comment by DispatchCommit** [comment]
Node 10+ should work. Our build pipeline tests 10, 12.
Node 8 recently began to start failing and has been removed.

**Comment by todokku** [comment]
which npm version ?

**Comment by DispatchCommit** [comment]
I'm not sure what the minimum version is, but likely 6.X would work. I know 6.10 or newer for sure works though.
