### ISSUE TITLE
heroku deploy problem

### ISSUE THREAD

**Issue by todokku** [bitwave-tv/bitwave#103]
Hi Bitwave ,
my deploy full log :
[https://gist.githubusercontent.com/todokku/3d19214410b204ad95a686ad4f1d044e/raw/24c55fa7e0aedb811b0848b9ae19b4fed6fea027/heroku%2520build%2520problem%2520bitwave](url)
My dyno Config Vars (.env vars) : 
APP_DEBUG=false
BITWAVE_ENV=production
NODE_ENV=production
PORT=3000
Buildpack:
heroku/nodejs
but app can't run : 
[https://bitwave.herokuapp.com/](url)
waiting for your response
finest regards
goodbye

**Comment by DispatchCommit** [comment]
Corrected log link: https://gist.github.com/todokku/3d19214410b204ad95a686ad4f1d044e

Will investigate requirements for heroku.

**Comment by DispatchCommit** [comment]
It seems the log is cut early and doesn't describe the reason for the failure, can you double check there isn't more?
