### ISSUE TITLE
[REPLAYS] Channel avatar not loading & incorrect links for chat channel tags

### ISSUE THREAD

**Issue by JerryatricBird** [bitwave-tv/bitwave#113]
Avatar issue: When in a replay, such as in https://bitwave.tv/soap/replay/XYhZUjmiWqRLyKMiX8EQ, 
the channel avatar is replaced with an exclamation point. not sure if intentional.

Main issue:Currently, when on a webpage hosting a replay, the user cannot exit the replay by clicking on the channel tags of other users in chat. IT changes the url, but locks the viewer in an unusable purgatory page that includes:
an unusable player element
an exclamation point where the channel avatar should be
![Screen Shot 2020-03-14 at 4 27 36 PM](https://user-images.githubusercontent.com/62188008/76689875-cc38b600-6610-11ea-9ba8-a6fb93984855.png)

"global" in the channel label above chat. 
The above listed can be seen in the attached image, which was obtained by first going to https://bitwave.tv/soap/replay/XYhZUjmiWqRLyKMiX8EQ and then clicking on a phoneboned channel tag in chat. **This issue similarly arises when selecting a channel via the view counter. This issue does not happen when selecting a new channel via navigation menu.**

**Comment by DispatchCommit** [comment]
For future reference, it's better to create 2 separate issues when logging issues so that I can prioritize and resolve issues independently of each other.
