### ISSUE TITLE
BUG: Navigation Bar occasionally resets and only displays a few channels. 

### ISSUE THREAD

**Issue by JerryatricBird** [bitwave-tv/bitwave#114]
When watching a stream for a sufficiently long enough time, a glitch will occur where there will only be a few streams available in the navigation bar. These appear to be mainly be the NSFW streams only. 
![Screen Shot 2020-03-14 at 5 48 17 PM](https://user-images.githubusercontent.com/62188008/76691009-4cb0e400-661c-11ea-88df-108934e53fb5.png)

After a few minutes they slowly come back....
![Screen Shot 2020-03-14 at 5 50 47 PM](https://user-images.githubusercontent.com/62188008/76691018-5f2b1d80-661c-11ea-9602-bd93739a4583.png)

**Comment by DispatchCommit** [comment]
Issue confirmed.

Does *not* affect only SFW streams, but exact pattern is unclear. Possibly related to timing of when a stream goes offline. Still need to reproduce on a dev build for full logs.

Likely cause is the API server not responding in time when the list changes and falling back to a cached copy of data supplied by the service worker.

**Comment by DispatchCommit** [comment]
Unable to reproduce.

Likely was related to intermittent server issues from when primary ingestion server was hosted on a different server provider. Primary ingestion server has been moved to a more stable hosting provider and the issue appears to have resolved.
