### ISSUE TITLE
Feature Request for Replays: allow the editing of replay titles

### ISSUE THREAD

**Issue by JerryatricBird** [bitwave-tv/bitwave#115]
For those streamers (like spooky) who never change their stream title, I think it would be nice to let them change the name of their replays after the fact for clarification.

**Comment by DispatchCommit** [comment]
Editing replay titles is already available if the streamer goes to their replay tab and clicks on the stream title it will allow them to change it.

Though it would be nice to have a better UI / UX for it on the actual replay page as well.

**Comment by DispatchCommit** [comment]
Added in v1.10.1 - commit [b58dccf](https://github.com/bitwave-tv/bitwave/commit/b58dccf4b828c96b3ebceda64f2e0326bc04907f)

**Comment by DispatchCommit** [comment]
resolved in production.
