### ISSUE TITLE
Feature Request: Replay comments with timestamp functionality from the start. 

### ISSUE THREAD

**Issue by JerryatricBird** [bitwave-tv/bitwave#118]
Comments on bitwave replays at this phase would primarily be used for timestamps, so if it is possible, please implement timestamps (as links to the time in the replay) available from the start of comments sections.

**Comment by DispatchCommit** [comment]
Player supports jumping to timestamps specified in seconds with the `player.currentTime(timestamp)` function.

Will need to detect timestamps as `[hh:]mm:ss` via regex and replace with text buttons that call the function mentioned above, converting the formatted timestamp into seconds, and ensuring the timestamp is a valid timestamp.

**Comment by DispatchCommit** [comment]
Timestamps now fully supported and auto-recognized by the API server.
