### ISSUE TITLE
Hydration Data can be stale

### ISSUE THREAD

**Issue by DispatchCommit** [bitwave-tv/bitwave#153]
Investigate why mobile hydration data is occasionally very stale (20+ minutes).

**Comment by DispatchCommit** [comment]
Closing as difficult to reproduce, easily fixed by user, infrequent in occurrence if it is still occurring.

**Comment by diingus** [comment]
Wow... Victim blaming much??

**Comment by DispatchCommit** [comment]
It was `stale`.
