### ISSUE TITLE
[CHAT] Autocomplete should complete for @/: not the entire message

### ISSUE THREAD

**Issue by diingus** [bitwave-tv/bitwave#194]
If you write a message and go to the beginning of the message, then write @/: autocomplete breaks

**Comment by DispatchCommit** [comment]
Probably need to improve the regex query for autocomplete to prevent it from being too greedy.

**Comment by diingus** [comment]
It seems [it isn't a regex](https://github.com/bitwave-tv/bitwave/blob/3b7e743701a0ab58a891ac9571d686f7ef06f8f7/components/Chat/ChatInput.vue#L299).
Something like `^[\/@:]\S+(?:\s*?)` should fix it. Autocomplete doesn't complete command parameters, either.

**Comment by DispatchCommit** [comment]
resolved.
