### ISSUE TITLE
Feature Request: Dynamic Archives

### ISSUE THREAD

**Issue by JerryatricBird** [bitwave-tv/bitwave#195]
Archive toggle added next to the "Edit" and "restream" buttons underneath your own channel, for ease of use. In addition, dynamic archiving where a stream can begin and end archives mid-stream. This could be to only record the "proper" show without the "intro," in one use case. OR in the event that the streamer forgets to archive. OR in the event that a streamer wishes to split the archives into several parts. These have been common events in the past and streams have had to stop and restart, resulting in predictable viewer disengagement. 
As a side note, the implementation of this can very seamlessly lead to eventual development of "clips" where that same button at the bottom of the stream can be changed to a "clip" button for viewers to clip out whatever part of the stream they are viewing. I will Add a separate ticket for clips. 
![Archive button](https://user-images.githubusercontent.com/62188008/84633586-7987c800-aea5-11ea-9cc3-505da1cb3264.png)

**Comment by DispatchCommit** [comment]
This may not as challenging as I first thought.

API hooks appear to already exist actually.

**Comment by DispatchCommit** [comment]
v1.21.6 will trigger new API endpoints to start and stop recording mid stream.
