### ISSUE TITLE
Brave Push Notifications Fail

### ISSUE THREAD

**Issue by DispatchCommit** [bitwave-tv/bitwave#209]
![image](https://user-images.githubusercontent.com/45262335/85645584-04f41c80-b64f-11ea-9d45-0180dc188039.png)

Service work registration appears to fail, and FCM token returns `null`.

**Comment by datagutt** [comment]
Push Notifications in Brave have to be manually enabled, if i recall correctly:
![image](https://user-images.githubusercontent.com/67436/85738202-219c5d00-b700-11ea-9308-c814db91ec55.png)
"Use Google Services for push messaging"

**Comment by datagutt** [comment]
For what it's worth, FCM and service worker registration works on Bitwave with the "Use Google Services for Push messaging"-setting enabled.
I am using Bitwave with notifications just fine in Brave.

This seems like a documentation issue. Maybe a modal should be shown telling the user possible ways to solve this (such as enabling this setting)?

**Comment by DispatchCommit** [comment]
> This seems like a documentation issue.

This is becoming a common theme. Should probably detect Brave browser and inject additional information regarding enabling push notifications. Would be a good opportunity to also inject info about Apple preventing mobile push notifications.

Off-topic but tangentially related, documentation for the iOS "Add to homescreen" flow is needed.

Pinning this issue for now as this can serve as temporary (permanent) documentation for brave users.

**Comment by datagutt** [comment]
Brave can be detected through this method:
``(navigator.brave && await navigator.brave.isBrave() || false)``
According to the following article: https://www.ctrl.blog/entry/brave-user-agent-detection.html

**Comment by DispatchCommit** [comment]
Documentation added to popup confirmation dialog:
![image](https://user-images.githubusercontent.com/45262335/86575371-fbf72b00-bf2b-11ea-877d-ae701831135b.png)
