### ISSUE TITLE
Streaming with Profile: none / Tune: none may break ingestion

### ISSUE THREAD

**Issue by DispatchCommit** [bitwave-tv/bitwave#215]
Working in version: OBS 25.0.8

**Comment by DispatchCommit** [comment]
Issue is having no profile / no tune set in OBS.

**Comment by DispatchCommit** [comment]
FIx: open OBS settings -> output
Put in `advanced` mode with the dropdown at the top.

Ensure the following settings are correct for the streaming tab:
Keyframes: 1
Profile: High
Tune: Zerolatency

**Comment by elizanite** [comment]
ill never sleep with you xander

**Comment by DispatchCommit** [comment]
Submitted PR to OBS to include bitwave in the services list with recommended default settings.

**Comment by DispatchCommit** [comment]
This should have been resolved by this commit: 
https://github.com/bitwave-tv/bitwave-media-server/commit/62c0af7794f23fd4d6b75cc3726cffa7f816ec12#diff-b1c806065e6868a12a0c068377112cb63622961c9570dc025219c37ca6d772e5
