### ISSUE TITLE
Investigate Chat fetch() hydrate timeout

### ISSUE THREAD

**Issue by diingus** [bitwave-tv/bitwave#241]
it may be worth keeping the timeout here over the cleaner function call since the timeout is fairly vital to preventing server from locking up when unable to get a response from the chat API. This was 100% the case for `asyncData`, but this behavior may have been improved for the fetch command.

_Originally posted by @DispatchCommit in https://github.com/bitwave-tv/bitwave/pull/238_

**Comment by DispatchCommit** [comment]
Fetch removed as we cannot hydrate prior to connecting to chat.
