### ISSUE TITLE
Slash commands do not work

### ISSUE THREAD

**Issue by DispatchCommit** [bitwave-tv/bitwave#265]
`/ignore` and all unignore / channel related ignores
`/trolls` does not seem to work
whispers get doxxed
etc. etc.

**Comment by diingus** [comment]
Forced filtering (i.e. `forceFilter` action would only call `Array.filter()`, not reassign the filtered messages, causing old messages by trolls, ignore users, ignored channels to still appear.

`/ignore`d usernames would be saved in original casing, but get checked against a lowercase version. Just added a `toLowerCase()`

`/graph` wouldn't default to the fictional user `all` (which I've registered, btw), and would instead try to find the username `undefined`
