### ISSUE TITLE
Recursive ignores are broken

### ISSUE THREAD

**Issue by diingus** [bitwave-tv/bitwave#356]
This feature should be off by default. There are many problems with it as it is currently implemented. Mainly, it causes "ghost ignores" to occur. I have been testing this with several dummy accounts. @d @j and @tr, when ignored, and this feature is turned on, effectively censors (for the user) all messages containing "@d", "@j", and "@tr", that includes @dispatch, @jdanks420 (as an example), and @ any troll. I have tried to bring this to dispatch's attention but he is too dim to see it. Hopefully, the RFC Committee can offer a solution. 

- hitla

**Comment by JerryatricBird** [comment]
UH OH ITS A HITLA FEATURE WATCH OUT!
