### ISSUE TITLE
URGENT: COMPLETE LOSS OF ACCESS TO cdn.bitwave.tv IMAGES. 

### ISSUE THREAD

**Issue by JerryatricBird** [bitwave-tv/bitwave#383]
**Re-posted from QuestionC on discord:** Websites prove their identity via certificates, which are valid for a set time period. The certificate for cdn.bitwave.tv expired on Sunday, September 27, 2020.
**Since that time no avatars or emotes have loaded.**

**Comment by DispatchCommit** [comment]
SSL Cert replaced.
