### ISSUE TITLE
Removal of Warrant Canary

### ISSUE THREAD

**Issue by ghost** [bitwave-tv/bitwave#586]
Commit 85ea8356a2e9983262c7878aed1fd80a3058209e removes the warrant canary from Bitwave. 

Dispatch, can you offer an explanation to why you took this action? From an outside perspective, it looks like your shit is getting subpoenaed or seized, and either you're too embarrassed to admit it, or you're under a gag order.

**Comment by DispatchCommit** [comment]
Did you read the comments by another user on the commit you linked?
