### ISSUE TITLE
Allow chat input to expand vertically

### ISSUE THREAD

**Issue by DispatchCommit** [bitwave-tv/bitwave#61]

**Comment by diingus** [comment]
This feature was reverted to prevent a regression being pushed to upstream.

**Comment by DispatchCommit** [comment]
Requires substantial layering modifications to be made and additionally caused issues with inputs events as currently configured.

Would probably be simpler to create a v2 chat with this functionality included from the beginning than to attempt to modify the fragile input event handling code as it currently exists.
