### ISSUE TITLE
Consider Color Coding Chat Channel Tags

### ISSUE THREAD

**Issue by DispatchCommit** [bitwave-tv/bitwave#90]
Consider color coding the channel tags of users when in global chat and messages appear from non-local chats

**Comment by JerryatricBird** [comment]
Underrated proposal right here. You mean to say that in chat channel tags, they appear in BitWave Blue if it's the channel you are chatting in and grey if it is not the same channel you are in, right?

**Comment by DispatchCommit** [comment]
v1.24.12 added.
